function setQuestion() {
	  var inputValue =  '{ "QUESTION" : [' +
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "0",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Practice Task", "QUESTIONCONTENT": "Please register your question.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "1",  "PSEC" : "30",  "RSEC" : "90",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 1: Giving Advice", "QUESTIONCONTENT": "Please register your question.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "2",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 2: Talking about a Personal Experience", "QUESTIONCONTENT": "Please register your question.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "3",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "picture/sample_1.jpeg",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 3: Describing a Scene", "QUESTIONCONTENT": "Please register your question.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "4",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "picture/sample_1.jpeg",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 4: Making Predictions", "QUESTIONCONTENT": "Please register your question.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "5",  "PSEC" : "60",  "RSEC" : "0",  "IMG" : "picture/sample_2.jpeg",  "IMGCAPTION": "Please register your question.", "IMG2": "picture/sample_3.jpeg", "IMG2CAPTION": "Please register your question.", "IMG3": "picture/sample_4.jpeg", "IMG3CAPTION": "Please register your question.", "QUESTIONTITLE": "Speaking Task 5: Comparing and Persuading", "QUESTIONCONTENT": "Please register your question.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "Your family is suggesting another house. Persuade your family member that what you chose is more suitable by comparing the two." },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "6",  "PSEC" : "60",  "RSEC" : "60",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 6: Dealing with a Difficult Situation", "QUESTIONCONTENT": "Please register your question.", "QUESTIONCONTENTEXTRA": "Please register your question.", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "7",  "PSEC" : "30",  "RSEC" : "90",  "IMG" : "null",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 7: Expressing Opinions", "QUESTIONCONTENT": "Please register your question.", "QUESTIONCONTENTEXTRA": "Please register your question.", "SPECIALCONTENT" : "null" },'+ 
'{ "TESTNUMBER" : "0",  "TASKNUMBER" : "8",  "PSEC" : "30",  "RSEC" : "60",  "IMG" : "picture/sample_5.jpeg",  "IMGCAPTION": "null", "IMG2": "null", "IMG2CAPTION": "null", "IMG3": "null", "IMG3CAPTION": "null", "QUESTIONTITLE": "Speaking Task 8: Describing an Unusual Situation", "QUESTIONCONTENT": "Please register your question.", "QUESTIONCONTENTEXTRA": "null", "SPECIALCONTENT" : "null" }'+ 
	  ']}';

	var objQuestion = JSON.parse(inputValue);
	return objQuestion;
}